[package]
name = "vpin"
version = "0.1.0"
edition = "2021"
description = "Rust library for the virtual pinball ecosystem"
repository = "https://github.com/francisdb/vpin"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/vpin"

keywords = ["vpin", "visual-pinball", "virtual-pinball", "vpx"]
categories = ["games-and-emulation", "virtual-pinball"]

exclude = [
    "testdata/*",
]

[dependencies]
byteorder = "1.5.0"
bytes = "1.5.0"
cfb = "0.8.1"
encoding_rs = "0.8.33"
md2 = "0.10.2"
nom = "7.1.3"
serde_json = "1.0.107"
utf16string = "0.2.0"

[dev-dependencies]
dirs = "5.0.1"
pretty_assertions = "1.4.0"
rand = "0.8.5"
testdir = "0.8.1"
walkdir = "2.4.0"

